spring:
    application:
        name: expenzio-config-default

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: https://expenzio-discovery-server-production.up.railway.app/eureka/
    instance:
        prefer-ip-address: true
