spring:
    application:
        name: expenzio-config-dev
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/springbootdb
        username: root
        password: aditya

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defalutZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
